### ISSUE TITLE
Unable to Access the Dataset Dropbox Link

### ISSUE THREAD

**Issue by CircleRadon** [Sid2697/HOI-Ref#6]
Hi, 
I am currently unable to access the [Dropbox link](https://www.dropbox.com/scl/fo/j0doida6jw4cyptyb20lz/AJllCPfePoXA0uYDjyzju94?rlkey=mn8yw12ebvos890kupxmrvb7t&dl=0) for the `HOI-QA` dataset.
Could you please help check it out?
Thank you!

**Comment by Sid2697** [comment]
Hello @CircleRadon ,

Can you please share the error that you're getting? Because I am able to access the Dropbox link in private mode as well (see the screenshot).

<img width="1624" alt="Screenshot 2024-11-19 at 06 57 09" src="https://github.com/user-attachments/assets/df771b89-5cf8-4bf1-bdb4-93a6abade36e">

**Comment by CircleRadon** [comment]
Thanks for your reply. I can now access the link.

**Comment by CircleRadon** [comment]
Thanks for your reply. I can now access the link.
